package org.mastermold.platform.common.validation

import cats.instances.all._

package object interpreters {

  val validatorsErrorMessages: ErrorMessagesCollection =
  StringValidationApplicationEntitiesServiceApplicativeErrorInterpreter.rawErrorMessages ++
  StringValidationCreditCardServiceApplicativeErrorInterpreter.rawErrorMessages

  object stringValidationCreditCardService extends StringValidationCreditCardServiceApplicativeErrorInterpreter

  object stringValidationJavaLiteralsService extends StringValidationJavaLiteralsServiceInterpreter

  object stringValidationService extends StringValidationServiceApplicativeErrorInterpreter

  object stringValidationApplicationEntities
      extends StringValidationApplicationEntitiesServiceApplicativeErrorInterpreter

}
