// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.6.2.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in Compile ++= {
  if (!(sbtLockHashIsUpToDate in ThisBuild).value && sbtLockIgnoreOverridesOnStaleHash.value) {
    Seq.empty
  } else {
    Seq(
      )
  }
}
// LIBRARY_DEPENDENCIES_HASH c89282f2f1c671ba135e6795abdaac655a521eff
