// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.6.2.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in Compile ++= {
  if (!(sbtLockHashIsUpToDate in ThisBuild).value && sbtLockIgnoreOverridesOnStaleHash.value) {
    Seq.empty
  } else {
    Seq(
      "com.chuusai"   % "shapeless_2.12"    % "2.3.3",
      "org.scalaz"    % "scalaz-core_2.12"  % "7.3.1",
      "org.typelevel" % "cats-core_2.12"    % "1.6.1",
      "org.typelevel" % "cats-kernel_2.12"  % "1.6.1",
      "org.typelevel" % "cats-macros_2.12"  % "1.6.1",
      "org.typelevel" % "machinist_2.12"    % "0.6.6",
      "org.typelevel" % "macro-compat_2.12" % "1.1.1"
    )
  }
}
// LIBRARY_DEPENDENCIES_HASH bc56d9dc7d5291a4f32224b60f5fcd7973169619
