// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.6.2.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides in Compile ++= {
  if (!(sbtLockHashIsUpToDate in ThisBuild).value && sbtLockIgnoreOverridesOnStaleHash.value) {
    Seq.empty
  } else {
    Seq(
      "co.fs2"                 % "fs2-core_2.12"                                  % "2.1.0",
      "co.fs2"                 % "fs2-io_2.12"                                    % "0.10.6",
      "co.fs2"                 % "fs2-scodec_2.12"                                % "0.10.6",
      "com.chuusai"            % "shapeless_2.12"                                 % "2.3.3",
      "com.lihaoyi"            % "sourcecode_2.12"                                % "0.1.8",
      "com.twitter"            % "hpack"                                          % "1.0.2",
      "dev.zio"                % "izumi-reflect-thirdparty-boopickle-shaded_2.12" % "0.12.0-M0",
      "dev.zio"                % "izumi-reflect_2.12"                             % "0.12.0-M0",
      "dev.zio"                % "zio-stacktracer_2.12"                           % "1.0.0-RC18-2",
      "dev.zio"                % "zio_2.12"                                       % "1.0.0-RC18-2",
      "io.circe"               % "circe-core_2.12"                                % "0.9.3",
      "io.circe"               % "circe-jawn_2.12"                                % "0.9.3",
      "io.circe"               % "circe-numbers_2.12"                             % "0.9.3",
      "org.eclipse.jetty.alpn" % "alpn-api"                                       % "1.1.3.v20160715",
      "org.http4s"             % "blaze-core_2.12"                                % "0.12.13",
      "org.http4s"             % "blaze-http_2.12"                                % "0.12.13",
      "org.http4s"             % "http4s-blaze-client_2.12"                       % "0.18.24",
      "org.http4s"             % "http4s-blaze-core_2.12"                         % "0.18.24",
      "org.http4s"             % "http4s-blaze-server_2.12"                       % "0.18.24",
      "org.http4s"             % "http4s-circe_2.12"                              % "0.18.24",
      "org.http4s"             % "http4s-client_2.12"                             % "0.18.24",
      "org.http4s"             % "http4s-core_2.12"                               % "0.18.24",
      "org.http4s"             % "http4s-dsl_2.12"                                % "0.18.24",
      "org.http4s"             % "http4s-jawn_2.12"                               % "0.18.24",
      "org.http4s"             % "http4s-server_2.12"                             % "0.18.24",
      "org.http4s"             % "http4s-websocket_2.12"                          % "0.2.1",
      "org.http4s"             % "jawn-fs2_2.12"                                  % "0.12.2",
      "org.http4s"             % "parboiled_2.12"                                 % "1.0.1",
      "org.javadelight"        % "delight-nashorn-sandbox"                        % "0.1.28",
      "org.log4s"              % "log4s_2.12"                                     % "1.7.0",
      "org.scala-lang.modules" % "scala-collection-compat_2.12"                   % "2.1.2",
      "org.scala-lang.modules" % "scala-xml_2.12"                                 % "1.2.0",
      "org.scalaz"             % "scalaz-core_2.12"                               % "7.3.1",
      "org.scodec"             % "scodec-bits_2.12"                               % "1.1.12",
      "org.slf4j"              % "slf4j-api"                                      % "1.7.25",
      "org.spire-math"         % "jawn-parser_2.12"                               % "0.11.1",
      "org.tpolecat"           % "doobie-core_2.12"                               % "0.8.6",
      "org.tpolecat"           % "doobie-free_2.12"                               % "0.8.6",
      "org.typelevel"          % "cats-core_2.12"                                 % "2.0.0",
      "org.typelevel"          % "cats-effect_2.12"                               % "2.0.0",
      "org.typelevel"          % "cats-free_2.12"                                 % "2.0.0",
      "org.typelevel"          % "cats-kernel_2.12"                               % "2.0.0",
      "org.typelevel"          % "cats-macros_2.12"                               % "2.0.0",
      "org.typelevel"          % "macro-compat_2.12"                              % "1.1.1",
      "org.webjars.bower"      % "js-beautify"                                    % "1.9.0"
    )
  }
}
// LIBRARY_DEPENDENCIES_HASH 02227ab6084791a38e9359ffe81941e09bbc657e
